# Generated by Django 3.2.9 on 2022-03-19 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20220219_1539'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='invoiceType',
            field=models.CharField(choices=[('On a monthly basis', 'On a monthly basis'), ('One time invoice (at the completion of assignment)', 'One time invoice (at the completion of assignment)')], max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='request',
            name='language',
            field=models.CharField(choices=[('Finnish', 'Finnish'), ('English', 'English'), ('Swedish', 'Swedish'), ('Other (specify in additional info)', 'Other (specify in additional info)')], max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='request',
            name='offerMaker',
            field=models.CharField(choices=[('Legal Office', 'Legal Office'), ('Legal Office (min. 5 lawyers)', 'Legal Office (min. 5 lawyers)'), ('Legal Office (min. 15 lawyers)', 'Legal Office (min. 15 lawyers)'), ('Law Firm', 'Law Firm'), ('Law Firm (min. 5 lawyers)', 'Law Firm (min. 5 lawyers)'), ('Law Firm (min. 15 lawyers)', 'Law Firm (min. 15 lawyers)')], max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='request',
            name='offerTime',
            field=models.CharField(choices=[('24 hours', '24 hours'), ('48 hours', '48 hours'), ('7 days', '7 days')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='request',
            name='hourCount',
            field=models.CharField(choices=[('Corporate law (0-5 hours)', 'Corporate law (0-5 hours)'), ('Employment law (10 hours)', 'Employment law (10 hours)'), ('IFR (20 hours)', 'IFR (20 hours)'), ('Other (specify in additional info)', 'Other (specify in additional info)')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='request',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='request',
            name='requestType',
            field=models.CharField(choices=[('Contract', 'Contract'), ('Day-to-day advice per month', 'Day-to-day advice per month'), ('Family documents', 'Family documents'), ('Inheritance documents', 'Inheritance documents'), ('Insolvency documents', 'Insolvency documents'), ('Other (specify in additional info)', 'Other (specify in additional info)')], max_length=200, null=True),
        ),
    ]
