# Generated by Django 3.2.9 on 2022-05-27 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20220327_1459'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='dateConfirm',
            field=models.CharField(choices=[('No', 'No'), ('Yes', 'Yes')], default='No', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='request',
            name='legalTopic',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='request',
            name='trainingDuration',
            field=models.CharField(choices=[('1 hour', '1 hour'), ('2 hours', '2 hours'), ('4 hours', '4 hours'), ('1 full day', '1 full day'), ('2 full days', '2 full days')], max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='request',
            name='trainingPlace',
            field=models.CharField(choices=[('Specify place below', 'Specify place below'), ('Remotely (e.g. over Microsoft Teams), with invite to be sent by you to your legal service provider', 'Remotely (e.g. over Microsoft Teams), with invite to be sent by you to your legal service provider'), ('Location to be confirmed later (possible additional travel time and costs may be invoiced separately by your legal service provider)', 'Location to be confirmed later (possible additional travel time and costs may be invoiced separately by your legal service provider)')], max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='request',
            name='trainingPlaceInfo',
            field=models.TextField(blank=True, null=True),
        ),
    ]
