# Generated by Django 3.2.9 on 2022-05-27 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20220527_1648'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='trainingDate',
            field=models.DateTimeField(null=True),
        ),
    ]
