# Generated by Django 3.2.9 on 2022-06-05 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_request_trainingdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='corpCompany',
            field=models.CharField(choices=[('Private limited company (osakeyhtiö)', 'Private limited company (osakeyhtiö)'), ('Public  limited company (julkinen  osakeyhtiö)', 'Public  limited company (julkinen  osakeyhtiö)')], max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='request',
            name='corpPreparation',
            field=models.CharField(choices=[('Preparation of meeting minutes (includes acting as secretary in the relevant meeting(s))', 'Preparation of meeting minutes (includes acting as secretary in the relevant meeting(s))'), ('Preparation of filings to the Finnish Trade Register', 'Preparation of filings to the Finnish Trade Register')], max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='request',
            name='legalAreas',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='request',
            name='legalHours',
            field=models.CharField(blank=True, choices=[('5', '5'), ('10', '10'), ('15', '15'), ('20', '20')], max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='request',
            name='legalMonths',
            field=models.CharField(blank=True, choices=[('12', '12'), ('24', '24'), ('36', '36')], max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='request',
            name='legalOffers',
            field=models.CharField(blank=True, choices=[('Hourly rate for legal advice as may be needed from time to time. Billed monthly.', 'Hourly rate for legal advice as may be needed from time to time. Billed monthly.'), ('Fixed price for a set number of hours of legal advice per month.', 'Fixed price for a set number of hours of legal advice per month.')], max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='request',
            name='privacyBusinessLine',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='request',
            name='privacyEmployeeCount',
            field=models.CharField(choices=[('0-10', '0-10'), ('10-25', '10-25'), ('25-100', '25-100'), ('100-1000', '100-1000'), ('1000+', '1000+')], max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='request',
            name='privacyGDPR',
            field=models.CharField(choices=[('Before May 2016', 'Before May 2016'), ('After May 2016', 'After May 2016'), ("I don't know", "I don't know")], max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='request',
            name='privacyOptions',
            field=models.CharField(choices=[('1. Holistic review of your company’s current level of compliance with data privacy legislation applicable in Finland, including written report of findings – FIXED PRICE', '1. Holistic review of your company’s current level of compliance with data privacy legislation applicable in Finland, including written report of findings – FIXED PRICE'), ('1. + Performance of corrective actions needed to remedy any deficiencies identified in the review (e.g. preparation of data privacy statement(s) and/or other necessary documentation, if missing) – FIXED PRICE', '1. + Performance of corrective actions needed to remedy any deficiencies identified in the review (e.g. preparation of data privacy statement(s) and/or other necessary documentation, if missing) – FIXED PRICE')], max_length=400, null=True),
        ),
        migrations.AddField(
            model_name='request',
            name='privacyReview',
            field=models.CharField(choices=[('No', 'No'), ('Yes', 'Yes')], max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='request',
            name='trainingTime',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='request',
            name='trainingDate',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='request',
            name='trainingPlace',
            field=models.CharField(choices=[('Specify place below', 'Specify place below'), ('Remotely (e.g. over Microsoft Teams), with invite to be sent by you to your legal service provider', 'Remotely (e.g. over Microsoft Teams), with invite to be sent by you to your legal service provider'), ('Location to be confirmed later (possible additional costs may be invoiced separately by your legal service provider)', 'Location to be confirmed later (possible additional costs may be invoiced separately by your legal service provider)')], max_length=200, null=True),
        ),
    ]
