# Generated by Django 3.2.9 on 2022-07-31 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_auto_20220618_1349'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='arbiArea',
            field=models.CharField(blank=True, choices=[('Holistic legal representation in arbitration proceedings (a)', 'Holistic legal representation in arbitration proceedings (a)'), ('Occasional support with arbitration proceedings (b)', 'Occasional support with arbitration proceedings (b)')], max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='request',
            name='arbiRole',
            field=models.CharField(blank=True, choices=[('Claimant', 'Claimant'), ('Defendant', 'Defendant')], max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='request',
            name='courtArea',
            field=models.CharField(blank=True, choices=[('Holistic legal representation in court dispute (a)', 'Holistic legal representation in court dispute (a)'), ('Occasional support with court dispute (b)', 'Occasional support with court dispute (b)')], max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='request',
            name='courtRole',
            field=models.CharField(blank=True, choices=[('Claimant', 'Claimant'), ('Defendant', 'Defendant')], max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='request',
            name='mergerArea',
            field=models.CharField(blank=True, choices=[('Holistic legal representation (1)', 'Holistic legal representation (1)'), ('Occasional support (2)', 'Occasional support (2)'), ('Short form LDD report (3)', 'Short form LDD report (3)'), ('Long form LDD report (4)', 'Long form LDD report (4)')], max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='request',
            name='mergerBusinessLine',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='request',
            name='mergerRange',
            field=models.CharField(blank=True, choices=[('0-100 kEUR', '0-100 kEUR'), ('100 kEUR-1 mEUR', '100 kEUR-1 mEUR'), ('1-10 mEUR', '1-10 mEUR'), ('10-50 mEUR', '10-50 mEUR'), ('50+ mEUR', '50+ mEUR')], max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='request',
            name='settlementArea',
            field=models.CharField(blank=True, choices=[('Holistic legal representation in settlement negotiations (a)', 'Holistic legal representation in settlement negotiations (a)'), ('Occasional support with settlement negotiations (b)', 'Occasional support with settlement negotiations (b)')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='request',
            name='mergerCompany',
            field=models.CharField(blank=True, choices=[('Private Company', 'Private Company'), ('Public Company', 'Public Company'), ('Private Person', 'Private Person')], max_length=200, null=True),
        ),
    ]
