# Generated by Django 3.2.9 on 2022-08-21 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_auto_20220807_1444'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='agreementBuyer',
            field=models.CharField(choices=[('Buying', 'Buying'), ('Selling', 'Selling')], max_length=400, null=True),
        ),
        migrations.AddField(
            model_name='request',
            name='agreementDescription',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='request',
            name='agreementInspection',
            field=models.CharField(choices=[('No', 'No'), ('Yes', 'Yes')], max_length=400, null=True),
        ),
        migrations.AddField(
            model_name='request',
            name='agreementRange',
            field=models.CharField(choices=[('0-100 kEUR', '0-100 kEUR'), ('100 kEUR-1 mEUR', '100 kEUR-1 mEUR'), ('1-10 mEUR', '1-10 mEUR'), ('10-50 mEUR', '10-50 mEUR'), ('50+ mEUR', '50+ mEUR')], max_length=400, null=True),
        ),
        migrations.AddField(
            model_name='request',
            name='constructionAgreement',
            field=models.CharField(choices=[('Contractor (seller)', 'Contractor (seller)'), ('Client (buyer)', 'Client (buyer)')], max_length=400, null=True),
        ),
        migrations.AddField(
            model_name='request',
            name='constructionDescription',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='request',
            name='constructionRange',
            field=models.CharField(choices=[('0-100 kEUR', '0-100 kEUR'), ('100 kEUR-1 mEUR', '100 kEUR-1 mEUR'), ('1-10 mEUR', '1-10 mEUR'), ('10-50 mEUR', '10-50 mEUR'), ('50+ mEUR', '50+ mEUR')], max_length=400, null=True),
        ),
        migrations.AddField(
            model_name='request',
            name='employmentContract',
            field=models.CharField(choices=[('Employment Contract', 'Employment Contract'), ('Managing Director Contract', 'Managing Director Contract'), ('Mutual Termination Contract', 'Mutual Termination Contract')], max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='request',
            name='employmentPos',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='request',
            name='employmentTemplate',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='request',
            name='leaseAgreement',
            field=models.CharField(choices=[('Lease of business premises lease', 'Lease of business premises lease'), ('Lease of residential premise', 'Lease of residential premise')], max_length=400, null=True),
        ),
        migrations.AddField(
            model_name='request',
            name='leaseDescription',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='request',
            name='leaseRange',
            field=models.CharField(choices=[('0-1000 EUR', '0-1000 EUR'), ('1000 EUR-10 000 EUR', '1000 EUR-10 000 EUR'), ('10 000 EUR-50 000 EUR', '10 000 EUR-50 000 EUR'), ('50 000 EUR+', '50 000 EUR+')], max_length=400, null=True),
        ),
        migrations.AddField(
            model_name='request',
            name='leaseRole',
            field=models.CharField(choices=[('Tenant', 'Tenant'), ('Landlord', 'Landlord')], max_length=400, null=True),
        ),
        migrations.AddField(
            model_name='request',
            name='leasebackDescription',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='request',
            name='leasebackInspection',
            field=models.CharField(choices=[('No', 'No'), ('Yes', 'Yes')], max_length=400, null=True),
        ),
        migrations.AddField(
            model_name='request',
            name='leasebackRange',
            field=models.CharField(choices=[('0-100 kEUR', '0-100 kEUR'), ('100 kEUR-1 mEUR', '100 kEUR-1 mEUR'), ('1-10 mEUR', '1-10 mEUR'), ('10-50 mEUR', '10-50 mEUR'), ('50+ mEUR', '50+ mEUR')], max_length=400, null=True),
        ),
        migrations.AddField(
            model_name='request',
            name='leasebackSeller',
            field=models.CharField(choices=[('Seller and Tenant', 'Seller and Tenant'), ('Buyer and Landlord', 'Buyer and Landlord')], max_length=400, null=True),
        ),
        migrations.AddField(
            model_name='request',
            name='realestateAgreement',
            field=models.CharField(choices=[('Plot/Parcel of Land', 'Plot/Parcel of Land'), ('Shares in a real estate company or a housing association', 'Shares in a real estate company or a housing association')], max_length=400, null=True),
        ),
        migrations.AddField(
            model_name='request',
            name='sourcingComments',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='request',
            name='sourcingCustomized',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='request',
            name='sourcingGeneric',
            field=models.CharField(choices=[('Generic', 'Generic'), ('Customized', 'Customized')], max_length=400, null=True),
        ),
        migrations.AddField(
            model_name='request',
            name='sourcingLawyer',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='request',
            name='sourcingTemplate',
            field=models.CharField(choices=[('Products', 'Products'), ('Services', 'Services')], max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='request',
            name='dispParty',
            field=models.CharField(blank=True, choices=[('a Party to Court Proceedings', '(a/b) a Party to Court Proceedings'), ('a Party to Arbitration Proceedings', '(c/d) a Party to Arbitration Proceedings'), ('a Party to Settlement Negotiations', '(e/f) a Party to Settlement Negotiations')], max_length=200, null=True),
        ),
    ]
