# Generated by Django 3.2.9 on 2022-09-10 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_auto_20220821_1406'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='realConstruction',
            field=models.CharField(choices=[('Holistic legal representation', '(a) Holistic legal representation'), ('Occasional support', '(b) Occasional support'), ('First draft of construction agreement', '(c) First draft of construction agreement'), ('First draft of construction agreement + occasional support', '(d) First draft of construction agreement + occasional support')], max_length=400, null=True),
        ),
        migrations.AddField(
            model_name='request',
            name='realLease',
            field=models.CharField(choices=[('Holistic legal representation', '(a) Holistic legal representation'), ('Occasional support', '(b) Occasional support'), ('First draft of lease agreement', '(c) First draft of lease agreement'), ('First draft of lease agreement + occasional support', '(d) First draft of lease agreement + occasional support')], max_length=400, null=True),
        ),
        migrations.AddField(
            model_name='request',
            name='realLeaseBack',
            field=models.CharField(choices=[('Holistic legal representation', '(a) Holistic legal representation'), ('Occasional support', '(b) Occasional support'), ('First draft of sale and purchase and lease agreement', '(c) First draft of sale and purchase and lease agreement'), ('First draft of sale and purchase and lease agreement + occasional support', '(d) First draft of sale and purchase and lease agreement + occasional support')], max_length=400, null=True),
        ),
        migrations.AddField(
            model_name='request',
            name='realSalePurchase',
            field=models.CharField(choices=[('Holistic legal representation', '(a) Holistic legal representation'), ('Occasional support', '(b) Occasional support'), ('First draft of sale and purchase agreement', '(c) First draft of sale and purchase agreement'), ('First draft of sale and purchase agreement + occasional support', '(d) First draft of sale and purchase agreement + occasional support')], max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='request',
            name='offerMaker',
            field=models.CharField(choices=[('Attorneys-at-law (FI: asianajotoimistot)', 'Attorneys-at-law (FI: asianajotoimistot)'), ('Attorneys-at-law employing at least 5 lawyers', 'Attorneys-at-law employing at least 5 lawyers'), ('Attorneys-at-law employing at least 15 lawyers', 'Attorneys-at-law employing at least 15 lawyers'), ('Law firms (FI: lakiasiaintoimistot)', 'Law firms (FI: lakiasiaintoimistot)'), ('Law firms employing at least 5 lawyers', 'Law firms employing at least 5 lawyers'), ('Law firms employing at least 15 lawyers', 'Law firms employing at least 15 lawyers')], max_length=200, null=True),
        ),
    ]
