# Generated by Django 3.2.9 on 2022-09-11 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_auto_20220910_1246'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='b2bDate',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='request',
            name='otherInfo',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='request',
            name='invoiceType',
            field=models.CharField(choices=[('On a monthly basis, invoice sent at end of each calendar month', 'On a monthly basis, invoice sent at end of each calendar month'), ('On a quarterly basis, invoice sent at end of each quarter', 'On a quarterly basis, invoice sent at end of each quarter'), ('One time invoice upon completion of the assignment', 'One time invoice upon completion of the assignment')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='request',
            name='note',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='request',
            name='offerMaker',
            field=models.CharField(choices=[('Attorneys-at-law (FI: asianajotoimistot), any size', 'Attorneys-at-law (FI: asianajotoimistot), any size'), ('Attorneys-at-law, employing at least 5 lawyers', 'Attorneys-at-law, employing at least 5 lawyers'), ('Attorneys-at-law, employing at least 15 lawyers', 'Attorneys-at-law, employing at least 15 lawyers'), ('Law firms (FI: lakiasiaintoimistot), any size', 'Law firms (FI: lakiasiaintoimistot), any size'), ('Law firms, employing at least 5 lawyers', 'Law firms, employing at least 5 lawyers'), ('Law firms, employing at least 15 lawyers', 'Law firms, employing at least 15 lawyers')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='request',
            name='offerTime',
            field=models.CharField(choices=[('Within 24 hours', 'Within 24 hours'), ('Within 48 hours', 'Within 48 hours'), ('Within 7 days', 'Within 7 days')], max_length=200, null=True),
        ),
    ]
