# Generated by Django 3.2.9 on 2022-09-14 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_auto_20220911_1520'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='b2cDate',
            field=models.DateField(null=True),
        ),
    ]
