# Generated by Django 3.2.9 on 2022-10-05 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_request_b2cdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='easementProperty',
            field=models.CharField(choices=[('Encumbered', 'Encumbered'), ('Encumbering', 'Encumbering')], max_length=400, null=True),
        ),
        migrations.AddField(
            model_name='request',
            name='easementSupport',
            field=models.CharField(choices=[('Holistic legal representation throughout the easement agreement negotiation process (including but not limited to drafting of the easement agreement and related documents (excluding purely technical maps and other similar documents), required communications with the other property owner, participation in necessary easement related meetings with competent authorities, etc.)', '(a) Holistic legal representation'), ('Occasional support with the easement agreement negotiation process (e.g. commenting of the easement agreement documentation, legal advice during different stages of the process)', '(b) Occasional support'), ('First draft of the easement agreement (excluding purely technical maps and similar documents), ready for delivery to the other property owner', '(c) First draft of lease agreement'), ('First draft of the easement agreement (excluding purely technical maps and similar documents), ready for delivery to the other property owner and thereafter occasional support with the easement agreement process (e.g. further commenting of the easement agreement documentation, legal advice during different stages of the process)', '(d) First draft of lease agreement + occasional support')], max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='request',
            name='additionalInfo',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='request',
            name='agreementInspection',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='request',
            name='dateConfirm',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='No', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='request',
            name='leaseAgreement',
            field=models.CharField(choices=[('Lease of business premises', 'Lease of business premises'), ('Lease of residential premises', 'Lease of residential premises'), ('Lease of a plot or a parcel of land', 'Lease of a plot or a parcel of land')], max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='request',
            name='leasebackInspection',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='request',
            name='privacyReview',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='request',
            name='realConstruction',
            field=models.CharField(choices=[('Holistic legal representation throughout the transaction process (including but not limited to drafting of the construction agreement and related documents, required negotiations with the other party and completion of signing/closing related legal actions)', '(a) Holistic legal representation'), ('Occasional support with the transaction process (e.g. commenting of transactional documents, legal advice during different stages of the transaction)', '(b) Occasional support'), ('First draft of the construction agreement, ready for delivery to the other party', '(c) First draft of construction agreement'), ('First draft of the construction agreement, ready for delivery to the other party and thereafter occasional support with the transaction process (e.g. further commenting of transactional documents, legal advice during different stages of the transaction)', '(d) First draft of construction agreement + occasional support')], max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='request',
            name='realLease',
            field=models.CharField(choices=[('Holistic legal representation throughout the transaction process (including but not limited to drafting of the lease and related documents, required negotiations with the other party and completion of signing/closing related legal actions)', '(a) Holistic legal representation'), ('Occasional support with the transaction process (e.g. commenting of transactional documents, legal advice during different stages of the transaction)', '(b) Occasional support'), ('First draft of the lease agreement, ready for delivery to the other party', '(c) First draft of lease agreement'), ('First draft of the lease agreement, ready for delivery to the other party and thereafter occasional support with the transaction process (e.g. further commenting of transactional documents, legal advice during different stages of the transaction)', '(d) First draft of lease agreement + occasional support')], max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='request',
            name='realLeaseBack',
            field=models.CharField(choices=[('Holistic legal representation throughout the transaction process (including but not limited to drafting of the sale and leaseback agreement and related documents, required negotiations with the other party and completion of signing/closing related legal actions)', '(a) Holistic legal representation'), ('Occasional support with the transaction process (e.g. commenting of transactional documents, legal advice during different stages of the transaction)', '(b) Occasional support'), ('First draft of the sale and leaseback agreement, ready for delivery to the other party', '(c) First draft of sale and purchase and lease agreement'), ('First draft of the sale and leaseback agreement, ready for delivery to the other party and thereafter occasional support with the transaction process (e.g. further commenting of transactional documents, legal advice during different stages of the transaction)', '(d) First draft of sale and purchase and lease agreement + occasional support')], max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='request',
            name='realSalePurchase',
            field=models.CharField(choices=[('Holistic legal representation throughout the transaction process (including but not limited to drafting of the sale and purchase agreement and related documents, required negotiations with the other party and completion of signing/closing related legal actions)', '(a) Holistic legal representation'), ('Occasional support with the transaction process (e.g. commenting of transactional documents, legal advice during different stages of the transaction)', '(b) Occasional support'), ('First draft of the sale and purchase agreement, ready for delivery to the other party', '(c) First draft of sale and purchase agreement'), ('First draft of the sale and purchase agreement, ready for delivery to the buyer/seller and thereafter occasional support with the transaction process (e.g. further commenting of transactional documents, legal advice during different stages of the transaction)', '(d) First draft of sale and purchase agreement + occasional support')], max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='request',
            name='realestateAgreement',
            field=models.CharField(choices=[('Plot/Parcel of Land', 'Plot/Parcel of Land'), ('Shares in a Real Estate Company (FI: kiinteistöosakeyhtiö)', 'Shares in a Real Estate Company (FI: kiinteistöosakeyhtiö)'), ('Shares in a Housing Association (FI: asunto-osakeyhtiö)', 'Shares in a Housing Association (FI: asunto-osakeyhtiö)')], max_length=400, null=True),
        ),
    ]
