# Generated by Django 3.2.9 on 2022-10-16 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_auto_20221005_1339'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='constructionPrice',
            field=models.CharField(choices=[('0 - 50kEUR', '0 - 50kEUR'), ('50 - 100kEUR', '50 - 100kEUR'), ('100kEUR - 1mEUR', '100kEUR - 1mEUR'), ('1+mEUR', '1+mEUR')], max_length=400, null=True),
        ),
        migrations.AddField(
            model_name='request',
            name='dispDescription',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='request',
            name='sourcingType',
            field=models.CharField(choices=[('My own contract template', 'My own contract template'), ("Supplier's contract template", "Supplier's contract template")], max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='request',
            name='constructionAgreement',
            field=models.CharField(choices=[('Contractor (seller of construction services)', 'Contractor (seller of construction services)'), ('Client (buyer of construction services)', 'Client (buyer of construction services)')], max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='request',
            name='courtArea',
            field=models.CharField(blank=True, choices=[('Holistic legal representation in court proceedings', '(a) Holistic legal representation in court proceedings'), ('Occasional support with court proceedings', '(b) Occasional support with court proceedings')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='request',
            name='legalOffers',
            field=models.CharField(blank=True, choices=[('Single hourly rate for occasional legal advice in the amount needed from time to time. Billed monthly in arrears.', 'Single hourly rate for occasional legal advice in the amount needed from time to time. Billed monthly in arrears.'), ('Lump sum monthly price for a fixed number of hours of legal support per month. Billed monthly in arrears.', 'Lump sum monthly price for a fixed number of hours of legal support per month. Billed monthly in arrears.')], max_length=200, null=True),
        ),
    ]
