# Generated by Django 3.2.9 on 2022-11-13 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_auto_20221016_1337'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='invoiceTypeRunning',
            field=models.CharField(choices=[('On a monthly basis, invoice sent at end of each calendar month', 'On a monthly basis, invoice sent at end of each calendar month'), ('On a quarterly basis, invoice sent at end of each quarter', 'On a quarterly basis, invoice sent at end of each quarter')], max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='request',
            name='mergerOtherCompany',
            field=models.CharField(blank=True, choices=[('Private Limited Company', 'Private Limited Company'), ('Public Limited Company', 'Public Limited Company'), ('Private Person', 'Private Person')], max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='request',
            name='mergerTarget',
            field=models.CharField(blank=True, choices=[('Private Limited Company', 'Private Limited Company'), ('Public Limited Company', 'Public Limited Company')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='request',
            name='agreementRange',
            field=models.CharField(choices=[('0-100 kEUR', '0-100 kEUR'), ('100 kEUR - 1 mEUR', '100 kEUR - 1 mEUR'), ('1-10 mEUR', '1-10 mEUR'), ('10-50 mEUR', '10-50 mEUR'), ('50+ mEUR', '50+ mEUR')], max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='request',
            name='arbiArea',
            field=models.CharField(blank=True, choices=[('Holistic legal representation in arbitration proceedings (including e.g. drafting of legal briefs, representation in arbitration hearings, attorney-client communications)', '(a) Holistic legal representation in arbitration proceedings'), ('Occasional support with arbitration proceedings (e.g. commenting on legal briefs, periodic advice regarding legal strategy, etc.)', '(b) Occasional support with arbitration proceedings')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='request',
            name='constructionRange',
            field=models.CharField(choices=[('0-100 kEUR', '0-100 kEUR'), ('100 kEUR - 1 mEUR', '100 kEUR - 1 mEUR'), ('1-10 mEUR', '1-10 mEUR'), ('10-50 mEUR', '10-50 mEUR'), ('50+ mEUR', '50+ mEUR')], max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='request',
            name='courtArea',
            field=models.CharField(blank=True, choices=[('Holistic legal representation in court proceedings (including e.g. drafting of legal briefs, representation in court hearings, attorney-client communications)', '(a) Holistic legal representation in court proceedings'), ('Occasional support with court proceedings (e.g. commenting on legal briefs, periodic advice regarding legal strategy, etc.)', '(b) Occasional support with court proceedings')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='request',
            name='leasebackRange',
            field=models.CharField(choices=[('0-100 kEUR', '0-100 kEUR'), ('100 kEUR - 1 mEUR', '100 kEUR - 1 mEUR'), ('1-10 mEUR', '1-10 mEUR'), ('10-50 mEUR', '10-50 mEUR'), ('50+ mEUR', '50+ mEUR')], max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='request',
            name='mergerArea',
            field=models.CharField(blank=True, choices=[('Holistic legal representation throughout the transaction process (including but not limited to legal due diligence, drafting of the sale and purchase agreement and related documents, required negotiations with the other party and support with signing and closing related actions)', '(1) Holistic legal representation'), ('Occasional support with the transaction process (e.g. commenting of transactional documents, legal advice during different stages of the transaction)', '(2) Occasional support'), ('Legal due diligence regarding the target; reporting of findings with short form ”red flag” LDD report', '(3) Short form LDD report'), ('Legal due diligence regarding the target; reporting of findings with long form LDD report (comprehensive review of all legal matters related to the target, not only identified ”red flag” issues)', '(4) Long form LDD report')], max_length=330, null=True),
        ),
        migrations.AlterField(
            model_name='request',
            name='mergerCompany',
            field=models.CharField(blank=True, choices=[('Private Limited Company', 'Private Limited Company'), ('Public Limited Company', 'Public Limited Company'), ('Private Person', 'Private Person')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='request',
            name='mergerRange',
            field=models.CharField(blank=True, choices=[('0-100 kEUR', '0-100 kEUR'), ('100 kEUR - 1 mEUR', '100 kEUR - 1 mEUR'), ('1-10 mEUR', '1-10 mEUR'), ('10-50 mEUR', '10-50 mEUR'), ('50+ mEUR', '50+ mEUR')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='request',
            name='mergerType',
            field=models.CharField(choices=[('Shares (all shares)', 'Shares (all shares)'), ('Shares (majority of shares)', 'Shares (majority of shares)'), ('Shares (minority stake)', 'Shares (minority stake)'), ('Business', 'Business'), ('Specific asset(s)', 'Specific asset(s)')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='request',
            name='privacyOptions',
            field=models.CharField(choices=[('Holistic review of my company’s current level of compliance with data privacy legislation applicable in Finland, including written report of findings', '(a) Holistic review'), ('Holistic review of my company’s current level of compliance with data privacy legislation applicable in Finland, including written report of findings. Performance of corrective actions needed to remedy any deficiencies identified in the review (e.g. preparation of data privacy statement(s) and/or other necessary documentation, if missing)', '(b) Holistic review + performance of corrective actions')], max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='request',
            name='settlementArea',
            field=models.CharField(blank=True, choices=[('Holistic legal representation in settlement negotiations (including e.g. drafting of a settlement agreement, negotiations with the other party, attorney-client communications)', '(a) Holistic legal representation in settlement negotiations'), ('Occasional support with settlement negotiations (e.g. commenting on draft settlement agreement, periodic advice regarding legal strategy, etc.)', '(b) Occasional support with settlement negotiations')], max_length=200, null=True),
        ),
    ]
