# Generated by Django 3.2.9 on 2022-11-27 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_auto_20221113_1405'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='trainingPlace',
            field=models.CharField(choices=[('Specify place below (under "Other information")', 'Specify place below (under "Other information")'), ('Remotely (e.g. over Microsoft Teams), with invite to be sent by you to your Lexify service provider', 'Remotely (e.g. over Microsoft Teams), with invite to be sent by you to your Lexify service provider'), ('Location to be confirmed later (possible travel related costs may be invoiced separately by your legal service provider)', 'Location to be confirmed later (possible travel related costs may be invoiced separately by your legal service provider)')], max_length=200, null=True),
        ),
    ]
