# Generated by Django 3.2.9 on 2022-12-11 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_alter_request_trainingplace'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='company_id',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='username',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
