# Generated by Django 3.2.9 on 2023-01-15 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0022_rename_username_customer_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmploymentTemplateRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employmentTemplate', models.TextField(blank=True, null=True)),
                ('b2bDate', models.DateField(null=True)),
                ('otherInfo', models.TextField(blank=True, null=True)),
                ('offerMaker', models.CharField(choices=[('Attorneys-at-law (FI: asianajotoimistot), any size', 'Attorneys-at-law (FI: asianajotoimistot), any size'), ('Attorneys-at-law, employing at least 5 lawyers', 'Attorneys-at-law, employing at least 5 lawyers'), ('Attorneys-at-law, employing at least 15 lawyers', 'Attorneys-at-law, employing at least 15 lawyers'), ('Law firms (FI: lakiasiaintoimistot), any size', 'Law firms (FI: lakiasiaintoimistot), any size'), ('Law firms, employing at least 5 lawyers', 'Law firms, employing at least 5 lawyers'), ('Law firms, employing at least 15 lawyers', 'Law firms, employing at least 15 lawyers')], max_length=200, null=True)),
                ('title', models.CharField(max_length=200, null=True)),
                ('invoiceType', models.CharField(choices=[('On a monthly basis, invoice sent at end of each calendar month', 'On a monthly basis, invoice sent at end of each calendar month'), ('On a quarterly basis, invoice sent at end of each quarter', 'On a quarterly basis, invoice sent at end of each quarter'), ('One time invoice upon completion of the assignment', 'One time invoice upon completion of the assignment')], max_length=200, null=True)),
            ],
        ),
    ]
