# Generated by Django 3.2.9 on 2023-01-15 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0023_employmenttemplaterequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='employmenttemplaterequest',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
