# Generated by Django 3.2.9 on 2023-01-24 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0024_employmenttemplaterequest_date_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='employmenttemplaterequest',
            name='employment_conTemplate',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='employmenttemplaterequest',
            name='language',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
