# Generated by Django 3.2.9 on 2023-01-24 12:58

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0025_auto_20230124_1444'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employmenttemplaterequest',
            name='employment_conTemplate',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=50), default=[], size=5),
        ),
        migrations.AlterField(
            model_name='employmenttemplaterequest',
            name='language',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=50), default=[], size=5),
        ),
    ]
