# Generated by Django 3.2.9 on 2023-01-24 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0026_auto_20230124_1458'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employmenttemplaterequest',
            name='employment_conTemplate',
        ),
    ]
