# Generated by Django 3.2.9 on 2023-01-24 13:35

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0027_remove_employmenttemplaterequest_employment_contemplate'),
    ]

    operations = [
        migrations.AddField(
            model_name='employmenttemplaterequest',
            name='employment_conTemplate',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=50), default=list, size=5),
        ),
        migrations.AlterField(
            model_name='employmenttemplaterequest',
            name='language',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=50), default=list, size=5),
        ),
    ]
