# Generated by Django 3.2.9 on 2023-02-12 11:01

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0032_disputearbitrationrequest_disputecourtrequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='corporateRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('corpCompany', models.CharField(choices=[('Private limited company (osakeyhtiö)', 'Private limited company (osakeyhtiö)'), ('Public  limited company (julkinen  osakeyhtiö)', 'Public  limited company (julkinen  osakeyhtiö)')], max_length=200, null=True)),
                ('language', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=50), default=list, size=5)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('b2bDate', models.DateField(null=True)),
                ('otherInfo', models.TextField(blank=True, null=True)),
                ('offerMaker', models.CharField(choices=[('Attorneys-at-law (FI: asianajotoimistot), any size', 'Attorneys-at-law (FI: asianajotoimistot), any size'), ('Attorneys-at-law, employing at least 5 lawyers', 'Attorneys-at-law, employing at least 5 lawyers'), ('Attorneys-at-law, employing at least 15 lawyers', 'Attorneys-at-law, employing at least 15 lawyers'), ('Law firms (FI: lakiasiaintoimistot), any size', 'Law firms (FI: lakiasiaintoimistot), any size'), ('Law firms, employing at least 5 lawyers', 'Law firms, employing at least 5 lawyers'), ('Law firms, employing at least 15 lawyers', 'Law firms, employing at least 15 lawyers')], max_length=200, null=True)),
                ('title', models.CharField(max_length=200, null=True)),
                ('invoiceTypeRunning', models.CharField(choices=[('On a monthly basis, invoice sent at end of each calendar month', 'On a monthly basis, invoice sent at end of each calendar month'), ('On a quarterly basis, invoice sent at end of each quarter', 'On a quarterly basis, invoice sent at end of each quarter')], max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='dataRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('privacyOptions', models.CharField(choices=[('Holistic review of my company’s current level of compliance with data privacy legislation applicable in Finland, including written report of findings', '(a) Holistic review'), ('Holistic review of my company’s current level of compliance with data privacy legislation applicable in Finland, including written report of findings. Performance of corrective actions needed to remedy any deficiencies identified in the review (e.g. preparation of data privacy statement(s) and/or other necessary documentation, if missing)', '(b) Holistic review + performance of corrective actions')], max_length=400, null=True)),
                ('privacyReview', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=200, null=True)),
                ('privacyGDPR', models.CharField(choices=[('Before May 2016', 'Before May 2016'), ('After May 2016', 'After May 2016'), ("I don't know", "I don't know")], max_length=200, null=True)),
                ('privacyBusinessLine', models.TextField(blank=True, null=True)),
                ('privacyEmployeeCount', models.CharField(choices=[('0-10', '0-10'), ('10-25', '10-25'), ('25-100', '25-100'), ('100-1000', '100-1000'), ('1000+', '1000+')], max_length=200, null=True)),
                ('language', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=50), default=list, size=5)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('b2bDate', models.DateField(null=True)),
                ('otherInfo', models.TextField(blank=True, null=True)),
                ('offerMaker', models.CharField(choices=[('Attorneys-at-law (FI: asianajotoimistot), any size', 'Attorneys-at-law (FI: asianajotoimistot), any size'), ('Attorneys-at-law, employing at least 5 lawyers', 'Attorneys-at-law, employing at least 5 lawyers'), ('Attorneys-at-law, employing at least 15 lawyers', 'Attorneys-at-law, employing at least 15 lawyers'), ('Law firms (FI: lakiasiaintoimistot), any size', 'Law firms (FI: lakiasiaintoimistot), any size'), ('Law firms, employing at least 5 lawyers', 'Law firms, employing at least 5 lawyers'), ('Law firms, employing at least 15 lawyers', 'Law firms, employing at least 15 lawyers')], max_length=200, null=True)),
                ('title', models.CharField(max_length=200, null=True)),
                ('invoiceType', models.CharField(choices=[('On a monthly basis, invoice sent at end of each calendar month', 'On a monthly basis, invoice sent at end of each calendar month'), ('On a quarterly basis, invoice sent at end of each quarter', 'On a quarterly basis, invoice sent at end of each quarter'), ('One time invoice upon completion of the assignment', 'One time invoice upon completion of the assignment')], max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='disputeSettlementRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('settlementArea', models.CharField(blank=True, choices=[('Holistic legal representation in settlement negotiations (including e.g. drafting of a settlement agreement, negotiations with the other party, attorney-client communications)', '(a) Holistic legal representation in settlement negotiations'), ('Occasional support with settlement negotiations (e.g. commenting on draft settlement agreement, periodic advice regarding legal strategy, etc.)', '(b) Occasional support with settlement negotiations')], max_length=200, null=True)),
                ('dispDescription', models.TextField(null=True)),
                ('language', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=50), default=list, size=5)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('b2bDate', models.DateField(null=True)),
                ('otherInfo', models.TextField(blank=True, null=True)),
                ('offerMaker', models.CharField(choices=[('Attorneys-at-law (FI: asianajotoimistot), any size', 'Attorneys-at-law (FI: asianajotoimistot), any size'), ('Attorneys-at-law, employing at least 5 lawyers', 'Attorneys-at-law, employing at least 5 lawyers'), ('Attorneys-at-law, employing at least 15 lawyers', 'Attorneys-at-law, employing at least 15 lawyers'), ('Law firms (FI: lakiasiaintoimistot), any size', 'Law firms (FI: lakiasiaintoimistot), any size'), ('Law firms, employing at least 5 lawyers', 'Law firms, employing at least 5 lawyers'), ('Law firms, employing at least 15 lawyers', 'Law firms, employing at least 15 lawyers')], max_length=200, null=True)),
                ('title', models.CharField(max_length=200, null=True)),
                ('invoiceType', models.CharField(choices=[('On a monthly basis, invoice sent at end of each calendar month', 'On a monthly basis, invoice sent at end of each calendar month'), ('On a quarterly basis, invoice sent at end of each quarter', 'On a quarterly basis, invoice sent at end of each quarter'), ('One time invoice upon completion of the assignment', 'One time invoice upon completion of the assignment')], max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='mergerRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sellOrBuy', models.CharField(blank=True, choices=[('Buying', 'Buying'), ('Selling', 'Selling')], max_length=200, null=True)),
                ('mergerType', models.CharField(choices=[('Shares (all shares)', 'Shares (all shares)'), ('Shares (majority of shares)', 'Shares (majority of shares)'), ('Shares (minority stake)', 'Shares (minority stake)'), ('Business', 'Business'), ('Specific asset(s)', 'Specific asset(s)')], max_length=200, null=True)),
                ('mergerCompany', models.CharField(blank=True, choices=[('Private Limited Company', 'Private Limited Company'), ('Public Limited Company', 'Public Limited Company'), ('Private Person', 'Private Person')], max_length=200, null=True)),
                ('mergerOtherCompany', models.CharField(blank=True, choices=[('Private Limited Company', 'Private Limited Company'), ('Public Limited Company', 'Public Limited Company'), ('Private Person', 'Private Person')], max_length=200, null=True)),
                ('mergerTarget', models.CharField(blank=True, choices=[('Private Limited Company', 'Private Limited Company'), ('Public Limited Company', 'Public Limited Company')], max_length=200, null=True)),
                ('mergerBusinessLine', models.TextField(blank=True, null=True)),
                ('mergerRange', models.CharField(blank=True, choices=[('0-100 kEUR', '0-100 kEUR'), ('100 kEUR - 1 mEUR', '100 kEUR - 1 mEUR'), ('1-10 mEUR', '1-10 mEUR'), ('10-50 mEUR', '10-50 mEUR'), ('50+ mEUR', '50+ mEUR')], max_length=200, null=True)),
                ('mergerArea', models.CharField(blank=True, choices=[('Holistic legal representation throughout the transaction process (including but not limited to legal due diligence, drafting of the sale and purchase agreement and related documents, required negotiations with the other party and support with signing and closing related actions)', '(1) Holistic legal representation'), ('Occasional support with the transaction process (e.g. commenting of transactional documents, legal advice during different stages of the transaction)', '(2) Occasional support'), ('Legal due diligence regarding the target; reporting of findings with short form ”red flag” LDD report', '(3) Short form LDD report'), ('Legal due diligence regarding the target; reporting of findings with long form LDD report (comprehensive review of all legal matters related to the target, not only identified ”red flag” issues)', '(4) Long form LDD report')], max_length=330, null=True)),
                ('language', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=50), default=list, size=5)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('b2bDate', models.DateField(null=True)),
                ('otherInfo', models.TextField(blank=True, null=True)),
                ('offerMaker', models.CharField(choices=[('Attorneys-at-law (FI: asianajotoimistot), any size', 'Attorneys-at-law (FI: asianajotoimistot), any size'), ('Attorneys-at-law, employing at least 5 lawyers', 'Attorneys-at-law, employing at least 5 lawyers'), ('Attorneys-at-law, employing at least 15 lawyers', 'Attorneys-at-law, employing at least 15 lawyers'), ('Law firms (FI: lakiasiaintoimistot), any size', 'Law firms (FI: lakiasiaintoimistot), any size'), ('Law firms, employing at least 5 lawyers', 'Law firms, employing at least 5 lawyers'), ('Law firms, employing at least 15 lawyers', 'Law firms, employing at least 15 lawyers')], max_length=200, null=True)),
                ('title', models.CharField(max_length=200, null=True)),
                ('invoiceType', models.CharField(choices=[('On a monthly basis, invoice sent at end of each calendar month', 'On a monthly basis, invoice sent at end of each calendar month'), ('On a quarterly basis, invoice sent at end of each quarter', 'On a quarterly basis, invoice sent at end of each quarter'), ('One time invoice upon completion of the assignment', 'One time invoice upon completion of the assignment')], max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='trainingRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('legalTopic', models.TextField(blank=True, null=True)),
                ('trainingDuration', models.CharField(choices=[('1 hour', '1 hour'), ('2 hours', '2 hours'), ('4 hours', '4 hours'), ('1 full day', '1 full day'), ('2 full days', '2 full days')], max_length=200, null=True)),
                ('dateConfirm', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='No', max_length=200, null=True)),
                ('trainingDate', models.DateField(null=True)),
                ('trainingTime', models.TimeField(null=True)),
                ('trainingPlace', models.CharField(choices=[('Specify place below (under "Other information")', 'Specify place below (under "Other information")'), ('Remotely (e.g. over Microsoft Teams), with invite to be sent by you to your Lexify service provider', 'Remotely (e.g. over Microsoft Teams), with invite to be sent by you to your Lexify service provider'), ('Location to be confirmed later (possible travel related costs may be invoiced separately by your legal service provider)', 'Location to be confirmed later (possible travel related costs may be invoiced separately by your legal service provider)')], max_length=200, null=True)),
                ('trainingPlaceInfo', models.TextField(blank=True, null=True)),
                ('language', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=50), default=list, size=5)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('b2bDate', models.DateField(null=True)),
                ('otherInfo', models.TextField(blank=True, null=True)),
                ('offerMaker', models.CharField(choices=[('Attorneys-at-law (FI: asianajotoimistot), any size', 'Attorneys-at-law (FI: asianajotoimistot), any size'), ('Attorneys-at-law, employing at least 5 lawyers', 'Attorneys-at-law, employing at least 5 lawyers'), ('Attorneys-at-law, employing at least 15 lawyers', 'Attorneys-at-law, employing at least 15 lawyers'), ('Law firms (FI: lakiasiaintoimistot), any size', 'Law firms (FI: lakiasiaintoimistot), any size'), ('Law firms, employing at least 5 lawyers', 'Law firms, employing at least 5 lawyers'), ('Law firms, employing at least 15 lawyers', 'Law firms, employing at least 15 lawyers')], max_length=200, null=True)),
                ('title', models.CharField(max_length=200, null=True)),
            ],
        ),
    ]
