# Generated by Django 3.2.9 on 2023-03-01 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0035_customer_company_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='company_address',
            field=models.TextField(max_length=200, null=True),
        ),
    ]
