# Generated by Django 3.2.9 on 2023-05-29 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0038_employmenttemplaterequest_priceoffer'),
    ]

    operations = [
        migrations.AddField(
            model_name='b2brequest',
            name='ratingType',
            field=models.CharField(choices=[('No, all LSPs can tender.', 'No, all LSPs can tender.'), ('Yes, at least 2 stars', 'Yes, at least 2 stars'), ('Yes, at least 3 stars', 'Yes, at least 3 stars'), ('Yes, at least 4 stars', 'Yes, at least 4 stars'), ('Yes, at least 5 stars', 'Yes, at least 5 stars')], max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='account_role',
            field=models.CharField(choices=[('Client', 'Client'), ('Service Provider', 'Service Provider')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='employmentnegotiationrequest',
            name='employmentContract',
            field=models.CharField(choices=[('Employment Contract', 'Employment Contract'), ('Managing Director Contract', 'Managing Director Contract'), ('Mutual Termination Contract', 'Mutual Termination Contract'), ('Contract regarding Employment Benefits', 'Contract regarding Employment Benefits'), ('Settlement Agreement regarding a Dispute with the Employee', 'Settlement Agreement regarding a Dispute with the Employee'), ('Other Contract (Please describe the purpose of the contract below)', 'Other Contract (Please describe the purpose of the contract below)')], max_length=200, null=True),
        ),
    ]
