# Generated by Django 3.2.9 on 2023-07-13 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0040_auto_20230615_0707'),
    ]

    operations = [
        migrations.AddField(
            model_name='b2brequest',
            name='priceOffer',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='b2crequest',
            name='priceOffer',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='corporaterequest',
            name='priceOffer',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='datarequest',
            name='priceOffer',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='disputearbitrationrequest',
            name='priceOffer',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='disputecourtrequest',
            name='priceOffer',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='disputesettlementrequest',
            name='priceOffer',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='employmentdocumentrequest',
            name='priceOffer',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='employmentnegotiationrequest',
            name='priceOffer',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='legalrequest',
            name='priceOffer',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='mergerrequest',
            name='priceOffer',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='realestateconstructionrequest',
            name='priceOffer',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='realestateeasementrequest',
            name='priceOffer',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='realestateleasebackrequest',
            name='priceOffer',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='realestateleaserequest',
            name='priceOffer',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='realestatepurchaserequest',
            name='priceOffer',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='sourcingbustemplaterequest',
            name='priceOffer',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='sourcingsupagreementrequest',
            name='priceOffer',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='sourcingsuptemplaterequest',
            name='priceOffer',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='trainingrequest',
            name='priceOffer',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
