# Generated by Django 3.2.9 on 2024-01-14 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0041_auto_20230713_1815'),
    ]

    operations = [
        migrations.AddField(
            model_name='b2brequest',
            name='offerOperation',
            field=models.CharField(blank=True, choices=[('No, the legal service provider can be of any age', 'No, the legal service provider can be of any age'), ('Yes, the legal service provider has been in operation for at least 5 years', 'Yes, the legal service provider has been in operation for at least 5 years'), ('Yes, the legal service provider has been in operation for at least 20 years', 'Yes, the legal service provider has been in operation for at least 20 years')], max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='b2brequest',
            name='offerSize',
            field=models.CharField(blank=True, choices=[('No, the legal service provider can be of any size', 'No, the legal service provider can be of any size'), ('Yes, the legal service provider must employ at least 5 lawyers', 'Yes, the legal service provider must employ at least 5 lawyers'), ('Yes, the legal service provider must employ at least 15 lawyers', 'Yes, the legal service provider must employ at least 15 lawyers')], max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='b2crequest',
            name='offerOperation',
            field=models.CharField(choices=[('No, the legal service provider can be of any age', 'No, the legal service provider can be of any age'), ('Yes, the legal service provider has been in operation for at least 5 years', 'Yes, the legal service provider has been in operation for at least 5 years'), ('Yes, the legal service provider has been in operation for at least 20 years', 'Yes, the legal service provider has been in operation for at least 20 years')], max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='b2crequest',
            name='offerSize',
            field=models.CharField(choices=[('No, the legal service provider can be of any size', 'No, the legal service provider can be of any size'), ('Yes, the legal service provider must employ at least 5 lawyers', 'Yes, the legal service provider must employ at least 5 lawyers'), ('Yes, the legal service provider must employ at least 15 lawyers', 'Yes, the legal service provider must employ at least 15 lawyers')], max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='b2crequest',
            name='ratingType',
            field=models.CharField(choices=[('No, all legal service providers can tender.', 'No, all legal service providers can tender.'), ('Yes, at least 3 stars', 'Yes, at least 3 stars'), ('Yes, at least 4 stars', 'Yes, at least 4 stars')], max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='realestateconstructionrequest',
            name='offerOperation',
            field=models.CharField(choices=[('No, the legal service provider can be of any age', 'No, the legal service provider can be of any age'), ('Yes, the legal service provider has been in operation for at least 5 years', 'Yes, the legal service provider has been in operation for at least 5 years'), ('Yes, the legal service provider has been in operation for at least 20 years', 'Yes, the legal service provider has been in operation for at least 20 years')], max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='realestateconstructionrequest',
            name='offerSize',
            field=models.CharField(choices=[('No, the legal service provider can be of any size', 'No, the legal service provider can be of any size'), ('Yes, the legal service provider must employ at least 5 lawyers', 'Yes, the legal service provider must employ at least 5 lawyers'), ('Yes, the legal service provider must employ at least 15 lawyers', 'Yes, the legal service provider must employ at least 15 lawyers')], max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='realestateconstructionrequest',
            name='ratingType',
            field=models.CharField(choices=[('No, all legal service providers can tender.', 'No, all legal service providers can tender.'), ('Yes, at least 3 stars', 'Yes, at least 3 stars'), ('Yes, at least 4 stars', 'Yes, at least 4 stars')], max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='realestateeasementrequest',
            name='offerOperation',
            field=models.CharField(choices=[('No, the legal service provider can be of any age', 'No, the legal service provider can be of any age'), ('Yes, the legal service provider has been in operation for at least 5 years', 'Yes, the legal service provider has been in operation for at least 5 years'), ('Yes, the legal service provider has been in operation for at least 20 years', 'Yes, the legal service provider has been in operation for at least 20 years')], max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='realestateeasementrequest',
            name='offerSize',
            field=models.CharField(choices=[('No, the legal service provider can be of any size', 'No, the legal service provider can be of any size'), ('Yes, the legal service provider must employ at least 5 lawyers', 'Yes, the legal service provider must employ at least 5 lawyers'), ('Yes, the legal service provider must employ at least 15 lawyers', 'Yes, the legal service provider must employ at least 15 lawyers')], max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='realestateeasementrequest',
            name='ratingType',
            field=models.CharField(choices=[('No, all legal service providers can tender.', 'No, all legal service providers can tender.'), ('Yes, at least 3 stars', 'Yes, at least 3 stars'), ('Yes, at least 4 stars', 'Yes, at least 4 stars')], max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='realestateleasebackrequest',
            name='offerOperation',
            field=models.CharField(choices=[('No, the legal service provider can be of any age', 'No, the legal service provider can be of any age'), ('Yes, the legal service provider has been in operation for at least 5 years', 'Yes, the legal service provider has been in operation for at least 5 years'), ('Yes, the legal service provider has been in operation for at least 20 years', 'Yes, the legal service provider has been in operation for at least 20 years')], max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='realestateleasebackrequest',
            name='offerSize',
            field=models.CharField(choices=[('No, the legal service provider can be of any size', 'No, the legal service provider can be of any size'), ('Yes, the legal service provider must employ at least 5 lawyers', 'Yes, the legal service provider must employ at least 5 lawyers'), ('Yes, the legal service provider must employ at least 15 lawyers', 'Yes, the legal service provider must employ at least 15 lawyers')], max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='realestateleasebackrequest',
            name='ratingType',
            field=models.CharField(choices=[('No, all legal service providers can tender.', 'No, all legal service providers can tender.'), ('Yes, at least 3 stars', 'Yes, at least 3 stars'), ('Yes, at least 4 stars', 'Yes, at least 4 stars')], max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='realestateleaserequest',
            name='offerOperation',
            field=models.CharField(choices=[('No, the legal service provider can be of any age', 'No, the legal service provider can be of any age'), ('Yes, the legal service provider has been in operation for at least 5 years', 'Yes, the legal service provider has been in operation for at least 5 years'), ('Yes, the legal service provider has been in operation for at least 20 years', 'Yes, the legal service provider has been in operation for at least 20 years')], max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='realestateleaserequest',
            name='offerSize',
            field=models.CharField(choices=[('No, the legal service provider can be of any size', 'No, the legal service provider can be of any size'), ('Yes, the legal service provider must employ at least 5 lawyers', 'Yes, the legal service provider must employ at least 5 lawyers'), ('Yes, the legal service provider must employ at least 15 lawyers', 'Yes, the legal service provider must employ at least 15 lawyers')], max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='realestateleaserequest',
            name='ratingType',
            field=models.CharField(choices=[('No, all legal service providers can tender.', 'No, all legal service providers can tender.'), ('Yes, at least 3 stars', 'Yes, at least 3 stars'), ('Yes, at least 4 stars', 'Yes, at least 4 stars')], max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='realestatepurchaserequest',
            name='offerOperation',
            field=models.CharField(choices=[('No, the legal service provider can be of any age', 'No, the legal service provider can be of any age'), ('Yes, the legal service provider has been in operation for at least 5 years', 'Yes, the legal service provider has been in operation for at least 5 years'), ('Yes, the legal service provider has been in operation for at least 20 years', 'Yes, the legal service provider has been in operation for at least 20 years')], max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='realestatepurchaserequest',
            name='offerSize',
            field=models.CharField(choices=[('No, the legal service provider can be of any size', 'No, the legal service provider can be of any size'), ('Yes, the legal service provider must employ at least 5 lawyers', 'Yes, the legal service provider must employ at least 5 lawyers'), ('Yes, the legal service provider must employ at least 15 lawyers', 'Yes, the legal service provider must employ at least 15 lawyers')], max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='realestatepurchaserequest',
            name='ratingType',
            field=models.CharField(choices=[('No, all legal service providers can tender.', 'No, all legal service providers can tender.'), ('Yes, at least 3 stars', 'Yes, at least 3 stars'), ('Yes, at least 4 stars', 'Yes, at least 4 stars')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='b2brequest',
            name='offerMaker',
            field=models.CharField(choices=[('Attorneys-at-law (FI: asianajotoimistot)', 'Attorneys-at-law (FI: asianajotoimistot)'), ('Law firms (FI: lakiasiaintoimistot)', 'Law firms (FI: lakiasiaintoimistot)'), ('Both attorneys-at-law & law firms', 'Both attorneys-at-law & law firms')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='b2brequest',
            name='priceOffer',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='b2brequest',
            name='ratingType',
            field=models.CharField(blank=True, choices=[('No, all legal service providers can tender.', 'No, all legal service providers can tender.'), ('Yes, at least 3 stars', 'Yes, at least 3 stars'), ('Yes, at least 4 stars', 'Yes, at least 4 stars')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='b2crequest',
            name='offerMaker',
            field=models.CharField(choices=[('Attorneys-at-law (FI: asianajotoimistot)', 'Attorneys-at-law (FI: asianajotoimistot)'), ('Law firms (FI: lakiasiaintoimistot)', 'Law firms (FI: lakiasiaintoimistot)'), ('Both attorneys-at-law & law firms', 'Both attorneys-at-law & law firms')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='realestateconstructionrequest',
            name='constructionAgreement',
            field=models.CharField(choices=[('Property owner (buyer of construction services)', 'Property owner (buyer of construction services)'), ('Main contractor (as seller of construction services)', 'Main contractor (as seller of construction services)'), ('Main contractor (as buyer of subcontracted services)', 'Main contractor (as buyer of subcontracted services)'), ('Subcontractor (as seller of construction services)', 'Subcontractor (as seller of construction services)')], max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='realestateconstructionrequest',
            name='constructionPrice',
            field=models.CharField(choices=[('0-50 kEUR', '0-50 kEUR'), ('50-100 kEUR', '50-100 kEUR'), ('100 kEUR-1 mEUR', '100 kEUR-1 mEUR'), ('1-10 mEUR', '1-10 mEUR'), ('10 mEUR+', '10 mEUR+')], max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='realestateconstructionrequest',
            name='offerMaker',
            field=models.CharField(choices=[('Attorneys-at-law (FI: asianajotoimistot)', 'Attorneys-at-law (FI: asianajotoimistot)'), ('Law firms (FI: lakiasiaintoimistot)', 'Law firms (FI: lakiasiaintoimistot)'), ('Both attorneys-at-law & law firms', 'Both attorneys-at-law & law firms')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='realestateconstructionrequest',
            name='realConstruction',
            field=models.CharField(choices=[('Comprehensive legal support throughout the transaction process (including but not limited to drafting of the construction contract and related documents (excluding scope of work descriptions and other primarily technical appendices), required negotiations with the other party, etc.)', '(a) Comprehensive legal support'), ('Occasional legal support with the transaction process when needed (e.g. commenting of transactional documents, legal advice during different stages of the transaction)', '(b) Occasional legal support'), ('First draft of the construction contract, ready for delivery to the other party', '(c) First draft of construction contract')], max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='realestateeasementrequest',
            name='easementSupport',
            field=models.CharField(choices=[('Comprehensive legal support throughout the easement agreement negotiation process (including but not limited to drafting of the easement agreement and related document (excluding maps and other primarily technical documents), required communications with the other property owner, participation innecessary easement related meetings with competent authorities, etc.)', '(a) Comprehensive legal support'), ('Occasional legal support with the easement agreement negotiation process (e.g. commenting of the easement agreement documentation, legal advice during different stages of the process when needed)', '(b) Occasional legal support'), ('First draft of the easement agreement, ready for delivery to the other property owner', '(c) First draft of easement agreement')], max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='realestateeasementrequest',
            name='offerMaker',
            field=models.CharField(choices=[('Attorneys-at-law (FI: asianajotoimistot)', 'Attorneys-at-law (FI: asianajotoimistot)'), ('Law firms (FI: lakiasiaintoimistot)', 'Law firms (FI: lakiasiaintoimistot)'), ('Both attorneys-at-law & law firms', 'Both attorneys-at-law & law firms')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='realestateleasebackrequest',
            name='offerMaker',
            field=models.CharField(choices=[('Attorneys-at-law (FI: asianajotoimistot)', 'Attorneys-at-law (FI: asianajotoimistot)'), ('Law firms (FI: lakiasiaintoimistot)', 'Law firms (FI: lakiasiaintoimistot)'), ('Both attorneys-at-law & law firms', 'Both attorneys-at-law & law firms')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='realestateleasebackrequest',
            name='realLeaseBack',
            field=models.CharField(choices=[('Comprehensive legal support throughout the transaction process (including but not limited to drafting of the sale and purchase agreement, lease agreement and related legal documents, required negotiations with the counterparty and support with completion of signing/closing related legal items)', '(a) Comprehensive legal support'), ('Occasional legal support with the transaction process when needed (e.g. commenting of transactional documents, legal advice during different stages of the transaction)', '(b) Occasional legal support'), ('First drafts of the sale and leaseback agreement, ready for delivery to the other party', '(c) First drafts of sale and purchase and lease agreement')], max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='realestateleaserequest',
            name='leaseAgreement',
            field=models.CharField(choices=[('Lease of business premises', 'Lease of business premises'), ('Lease of residential premises', 'Lease of residential premises'), ('Lease of plot or parcel of land', 'Lease of plot or parcel of land')], max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='realestateleaserequest',
            name='leaseRange',
            field=models.CharField(choices=[('0-1 kEUR', '0-1 kEUR'), ('1-10 kEUR', '1-10 kEUR'), ('10-50 kEUR', '10-50 kEUR'), ('50 kEUR+', '50 kEUR+')], max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='realestateleaserequest',
            name='offerMaker',
            field=models.CharField(choices=[('Attorneys-at-law (FI: asianajotoimistot)', 'Attorneys-at-law (FI: asianajotoimistot)'), ('Law firms (FI: lakiasiaintoimistot)', 'Law firms (FI: lakiasiaintoimistot)'), ('Both attorneys-at-law & law firms', 'Both attorneys-at-law & law firms')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='realestateleaserequest',
            name='realLease',
            field=models.CharField(choices=[('Comprehensive legal support throughout the transaction process (including but not limited to drafting of the lease and related legal documents, required negotiations with the counterparty and completion of signing/closing related legal actions)', '(a) Comprehensive legal support'), ('Occasional legal support with the transaction process when needed (e.g. commenting of transactional documents, legal advice during different stages of the process)', '(b) Occasional legal support'), ('First draft of the lease agreement, ready for delivery to the other party', '(c) First draft of lease agreement')], max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='realestatepurchaserequest',
            name='offerMaker',
            field=models.CharField(choices=[('Attorneys-at-law (FI: asianajotoimistot)', 'Attorneys-at-law (FI: asianajotoimistot)'), ('Law firms (FI: lakiasiaintoimistot)', 'Law firms (FI: lakiasiaintoimistot)'), ('Both attorneys-at-law & law firms', 'Both attorneys-at-law & law firms')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='realestatepurchaserequest',
            name='realSalePurchase',
            field=models.CharField(choices=[('Comprehensive legal support throughout the transaction process (including but not limited to drafting of the sale and purchase agreement and related documents, required negotiations with the other party and related legal documents, required negotiations with the counterparty and support with completion of signing/closing related legal items)', '(a) Comprehensive legal support'), ('Occasional legal support with the transaction process when needed(e.g. commenting of transactional documents, legal advice during different stages of the transaction)', '(b) Occasional legal support'), ('First draft of the sale and purchase agreement, ready for delivery to the other party', '(c) First draft of sale and purchase agreement')], max_length=400, null=True),
        ),
    ]
