# Generated by Django 3.2.9 on 2024-01-14 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0042_auto_20240114_0554'),
    ]

    operations = [
        migrations.AlterField(
            model_name='b2brequest',
            name='offerOperation',
            field=models.CharField(blank=True, choices=[('No, the legal service provider can be of any age', 'No, the legal service provider can be of any age'), ('Yes, the legal service provider has been in operation for at least 5 years', 'Yes, the legal service provider has been in operation for at least 5 years'), ('Yes, the legal service provider has been in operation for at least 20 years', 'Yes, the legal service provider has been in operation for at least 20 years')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='b2brequest',
            name='offerSize',
            field=models.CharField(blank=True, choices=[('No, the legal service provider can be of any size', 'No, the legal service provider can be of any size'), ('Yes, the legal service provider must employ at least 5 lawyers', 'Yes, the legal service provider must employ at least 5 lawyers'), ('Yes, the legal service provider must employ at least 15 lawyers', 'Yes, the legal service provider must employ at least 15 lawyers')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='b2brequest',
            name='ratingType',
            field=models.CharField(blank=True, choices=[('No, all legal service providers can tender.', 'No, all legal service providers can tender.'), ('Yes, at least 3 stars', 'Yes, at least 3 stars'), ('Yes, at least 4 stars', 'Yes, at least 4 stars')], max_length=200, null=True),
        ),
    ]
